# Generated by Django 3.2.7 on 2021-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=30)),
                ('Dept', models.CharField(max_length=50)),
                ('Sem', models.IntegerField()),
                ('Section', models.CharField(max_length=1)),
                ('Batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=30)),
                ('Dept', models.CharField(max_length=50)),
            ],
        ),
    ]
