# Generated by Django 3.2.7 on 2022-01-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=50)),
                ('Sem', models.IntegerField()),
                ('Sec', models.CharField(max_length=1)),
                ('Sub_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.subject')),
                ('Teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.teacher')),
            ],
        ),
    ]
