# Generated by Django 3.2.7 on 2022-01-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_teaches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
