# Generated by Django 3.2.7 on 2022-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Mark',
            field=models.BooleanField(default=True),
        ),
    ]
