# Generated by Django 3.2.7 on 2022-01-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_attendance_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aicte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField()),
                ('Mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.teacher')),
                ('Usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
            ],
        ),
    ]
