# Generated by Django 3.2.7 on 2022-01-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_aicte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aicte',
            new_name='Mentor',
        ),
        migrations.CreateModel(
            name='AicteP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Point', models.IntegerField()),
                ('Usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.student')),
            ],
        ),
    ]
