# Generated by Django 3.2.7 on 2022-01-21 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20220121_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aictep',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
    ]
