# Generated by Django 3.2.7 on 2022-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20220121_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aictep',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
