# Generated by Django 3.2.7 on 2022-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_aictep_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aictep',
            name='Activity',
            field=models.CharField(max_length=50),
        ),
    ]
