# Generated by Django 3.2.7 on 2022-01-22 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_aictep_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Batch',
        ),
        migrations.AlterField(
            model_name='aictep',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 1, 22)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 1, 22)),
        ),
    ]
