# Generated by Django 3.2.7 on 2022-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20220123_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(),
        ),
    ]
