# Generated by Django 3.2.7 on 2022-01-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='Mentor',
            new_name='mentor_d',
        ),
    ]
