# Generated by Django 3.2.7 on 2022-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_rename_mentor_mentor_mentor_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aictep',
            name='Date',
            field=models.DateField(),
        ),
    ]
